import './globals.css'

export const metadata = {
  title: 'Next.js sandbox',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>Navbar!</nav>
        {children}
      </body>
    </html>
  )
}
